# Generated by Django 4.2.14 on 2024-07-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcatcher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tag', models.CharField(choices=[('S', 'Same'), ('D', 'Different'), ('H', 'Hybrid: Same+Different')], default='S', max_length=1)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamcatcher_app.dream')),
            ],
        ),
    ]
