# Generated by Django 4.2.14 on 2024-07-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamcatcher_app', '0002_dreamhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamhistory',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dreamhistory',
            name='date',
            field=models.DateField(verbose_name='Dream date'),
        ),
    ]
