# Generated by Django 4.2.14 on 2024-07-31 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreamcatcher_app', '0003_dreamhistory_description_alter_dreamhistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dreamhistory',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
